# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    container_name: db
    volumes: 
      - /data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
  
  exchange:
    build:
      context: .
      dockerfile: exchange.Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://root:root@mongo:27017/
      - MONGODB_DB_NAME=exchange
    depends_on:
      - mongo
    ports:
      - '9000:3000'
  
  bidder1:
    build:
      context: .
      dockerfile: bidder.Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://root:root@mongo:27017/
      - MONGODB_DB_NAME=bidder1
    depends_on:
      - mongo
    ports:
      - '10001:4000'

  bidder2:
    build:
      context: .
      dockerfile: bidder.Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://root:root@mongo:27017/
      - MONGODB_DB_NAME=bidder2
    depends_on:
      - mongo
    ports:
      - '10002:4000'
  

